minimum-gas-prices = ""

pruning = "default"

pruning-keep-recent = "0"
pruning-keep-every = "0"
pruning-interval = "0"

halt-height = 0

halt-time = 0

min-retain-blocks = 0

inter-block-cache = true

index-events = []

iavl-cache-size = 781250

iavl-disable-fastnode = true


[telemetry]

service-name = ""

enabled = false

enable-hostname = false

enable-hostname-label = false

enable-service-label = false

prometheus-retention-time = 0

global-labels = [
]


[api]

enable = false

swagger = false

address = "tcp://0.0.0.0:1317"

max-open-connections = 1000

rpc-read-timeout = 10

rpc-write-timeout = 0

rpc-max-body-bytes = 1000000

enabled-unsafe-cors = false


[rosetta]

enable = false

address = ":8080"

blockchain = "app"

network = "network"

retries = 3

offline = false


[grpc]

enable = true

address = "0.0.0.0:9090"


[grpc-web]

enable = true

address = "0.0.0.0:9091"

enable-unsafe-cors = false


[state-sync]

snapshot-interval = 1000

snapshot-keep-recent = 10
